library(dplyr)
unzip("exdata_data_NEI_data.zip")
SCC <- readRDS("Source_Classification_Code.rds")
NEI <- readRDS("summaryscc_PM25.rds")
str(SCC)
Vehicle <- subset(SCC, grepl("Vehicle", SCC.Level.Two))
scc <- Vehicle$SCC
selected <- filter(NEI, SCC %in% scc)
selected <- subset(selected, fips == "24510")
selected <- group_by(selected, year)
total_emission <- tapply(selected$Emissions, selected$year, sum)
png("plot5.png")
barplot(total_emission, col = "darkturquoise", xlab = "Year", ylab = "Total Emission in tons", main = "Total motor vehicle emissions in Baltimore City")
dev.off()